# Site settings
title:Abueng Junior
email:abuengntsimane@icloud.com
description: > We Start With Thinking, Not Design
baseurl: "" Design is what people see — strategy is what makes it work.
Our role is to help businesses understand their brands deeply, so every logo, website, campaign, and activation serves a clear purpose instead of just filling space.
url: "http://www.abbuengjunior.co.za"
linkedin_username:https://www.linkedin.com/in/abueng-junior/

# Build settings
markdown: kramdown
